### ISSUE TITLE
Getting access to each {{figma.children}}

### ISSUE THREAD

**Issue by damalekguide** [figma/code-snippet-editor-plugin#34]
Hello!
I'm working on making toggle button part of template, my toggle button is created in a way that it has always 2 node children.
I have this challenge to get label props to one place in template and then get other children inside tag, ideally it would look something like this:
```
<ToggleButtonGroup
  {{figma.children.0}}
>
  {{figma.children.1}}
</ToggleButtonGroup>
```
So I can get this outcome
```
<ToggleButtonGroup
  label="Toggle button"
>
    <ToggleButton
      label="First"
      value="first"
    />
    <ToggleButton
      label="Last"
      value="last"
    />
</ToggleButtonGroup>
```

Would that be something worth pursuing? Or is there a way to do that right now?

**Comment by jake-figma** [comment]
Oh yes, interesting use case you have here. I'm still thinking over this one in #6. There are some thoughts in there about filtering children which i prefer to a fixed order-dependent solution. No current support, but definitely on my mind to solve!

**Comment by ericandrewscott** [comment]
Sorry. I just saw this and perhaps opened a duplicate issue. I would be super interested in order-dependent checking or even guard railing by checking other properties or data on `figma.children[1]` or `figma.children.1`.
