### ISSUE TITLE
[Feature] IntelliJ IDEA

### ISSUE THREAD

**Issue by macorifice** [figma/code-snippet-editor-plugin#37]
Hey, it would be really cool to use this plugin on IntelliJ also !

Why?
Most developers in addition to VSCode also use IntelliJ as an editor

**Comment by jake-figma** [comment]
thanks for the feedback, this is feedback for figma, not the plugin. forwarding to our team, but [the forum](https://forum.figma.com/) is a better place for this sort of feedback in the future!
