### ISSUE TITLE
X and Y values not visible in raw data

### ISSUE THREAD

**Issue by mikeysouthwell** [figma/code-snippet-editor-plugin#41]
Hi Jake,

How do I get the margin values from the node?

I can't see the X or Y values in the raw data.

For example I have a badge on my notification icon and I need to know it's distance from the edges of the frame for positioning purposes. As shown in the screenshot below, the X value is 23 and Y value is 4. With the Width and Height values of the ellipse being 22.

![image](https://github.com/figma/code-snippet-editor-plugin/assets/32289412/3530f61a-f075-4821-ad9b-e4c3ed19964f)

{
    "node.name": "Ellipse",
    "node.type": "ELLIPSE",
    "css.width": "22px",
    "css.height": "22px",
    "css.flexShrink": "0",
    "css.fill": "var(--Red-Gradient, linear-gradient(180deg, #FB7474 7.29%, #F91F1F 100%))",
    "css.strokeWidth": "1px",
    "css.stroke": "var(--White, #FFF)"
}

**Comment by jake-figma** [comment]
this is a limitation of the css plugin api output. will keep this in mind as we think about other node values to surface. this is complex because these values are relative to the parent layout mode.
