### ISSUE TITLE
How to create json code for global template to output code for all selected components?

### ISSUE THREAD

**Issue by mikeysouthwell** [figma/code-snippet-editor-plugin#42]
Hi Jake,

How do I create a global template that works the same as the Frame with child nodes code, but for components?

Looking through the readme file, it looks like you have to know the component ID, but I want it to convert any component and its children to code. 

How do I create the code for this in the JSON file? The example below is where the ID of the component is known in advance, but I would want this to work for all components:

```JSON
"components": {
    "componentKeyABC123": [
      {
        "title": "Sample React",
        "language": "JAVASCRIPT",
        "code": "<MyComponent />"
      }
    ]
  }

**Comment by mikeysouthwell** [comment]
Hey Jake. Any update on this?

**Comment by ja-k-e** [comment]
hey @mikeysouthwell, this is jake, i’m out of office right now so i’m using my personal account. you can use the node type just like any other node. COMPONENT_SET, and COMPONENT should work just fine.

**Comment by jake-figma** [comment]
will add better documentation, but any node type can be referred to in the [global templates types namespace](https://github.com/figma/code-snippet-editor-plugin?tab=readme-ov-file#global-templates)
