### ISSUE TITLE
Exporting variables to code

### ISSUE THREAD

**Issue by mikeysouthwell** [figma/code-snippet-editor-plugin#43]
Hey Jake,

Would it be possible to use your plugin to export all the variables and styles out of Figma in a custom format that we set so it matches the code of our chosen platform?

As a simple example:
```XAML
<Color x:Key="White">#FFFFFF</Color>
```

**Comment by mikeysouthwell** [comment]
Being able to alter the "Key" value would also be handy so we can rename this for variables that are in subfolders or referencing other variables

eg. BaseCollection\NeutralsFolder\white-color

**Comment by jake-figma** [comment]
[variable names](https://github.com/figma/code-snippet-editor-plugin?tab=readme-ov-file#variables) are available as params, but there is not a good way to load all variables with a codegen plugin in dev mode.
