### ISSUE TITLE
Raw data missing from dev mode side menu when using global templates

### ISSUE THREAD

**Issue by mikeysouthwell** [figma/code-snippet-editor-plugin#47]
Hi Jake,

I can no longer see any of the code fields in the dev mode pane on the right apart from the global template editor code.

Has something changed?

![image](https://github.com/figma/code-snippet-editor-plugin/assets/32289412/48cc24ea-4177-49c9-afd2-91c7e21775e2)

**Comment by jake-figma** [comment]
[Details mode](https://github.com/figma/code-snippet-editor-plugin#details-mode) is enabled in the settings menu. If you changed browsers / native app, this setting is likely in its default state of disabled.

**Comment by mikeysouthwell** [comment]
Hi Jake,

Thanks for getting back to me.

I already have Details mode on and it hasn't made a difference. I even tried setting it to off and then back on again and it hasn't fixed it. Can you please take another look?

![image](https://github.com/figma/code-snippet-editor-plugin/assets/32289412/895582f0-dffe-4fb2-aca6-a64ed0fd9b14)

**Comment by jake-figma** [comment]
can you reload the tab (right click tab + "reload tab") and make sure that isnt all it is? i am unable to reproduce.

**Comment by mikeysouthwell** [comment]
Sorry Jake, I didn't see your reply for some reason. I have tried reloading. I have tried it using Figma desktop and browser and on multiple computers. This is still an issue.

**Comment by jake-figma** [comment]
is there an error in the console by chance? whats throwing me off is it isnt even showing the templates either (details mode should show you the template _and_ the snippet). all of details mode isnt working for you.

can we see if codegen settings are working at all for you? can you try toggling the "default snippet" setting on and off and see if that works?

default snippet: message (a generic message shows up)
![CleanShot 2024-03-18 at 10 36 23](https://github.com/figma/code-snippet-editor-plugin/assets/97200987/64226a4c-f966-4db7-9503-9acabf615030)

default snippet: empty (nothing shows up)
![CleanShot 2024-03-18 at 10 36 56](https://github.com/figma/code-snippet-editor-plugin/assets/97200987/5d442a90-b3ae-44e7-bacd-b1d47e7415a3)

**Comment by mikeysouthwell** [comment]
I do not get a message showing up at all, just the global template:

![image](https://github.com/figma/code-snippet-editor-plugin/assets/32289412/45039e46-2474-4169-a763-31ce94862191)

**Comment by jake-figma** [comment]
you have to select something that doesnt have a template on it in order for the default message to show up. right now it is showing the global template, so there is no default. if you select a path or some other node type that doesnt have a template on it, it will show you the default message.

**Comment by mikeysouthwell** [comment]
I have my global template applied to pretty much everything. The only thing I can think of that doesn't have it is an ellipse and that doesn't show any Snippets message when it's selected.

**Comment by jake-figma** [comment]
you can clear global templates temporarily by setting to `{}`. can you email me at `jalbaugh@figma.com` with an example file where this is happening? github issues arent great for this level of support.

**Comment by mikeysouthwell** [comment]
Hey Jake,

I have tried changing the global templates to {}, but it's still not showing any of the plain text data:

![image](https://github.com/figma/code-snippet-editor-plugin/assets/32289412/07e3dc13-d664-4cfd-980e-c05aa4d79fd3)

![image](https://github.com/figma/code-snippet-editor-plugin/assets/32289412/8fc9664d-422c-45a9-89fe-013bb504ad34)

**Comment by mikeysouthwell** [comment]
I've also granted that email address access to my Figma file and sent you an email.

Thanks Jake :)

**Comment by jake-figma** [comment]
will follow up via email but this is telling me codegen plugin settings arent being respected on your machine which could be a different bug.

**Comment by jake-figma** [comment]
For the record: this resolved itself some time after toggling the plugin as default on and off. There may have been an issue with conflict between client default setting and what was stored in the database for plugin settings. This would be a Figma plugin API bug, not a bug with this plugin, so if this happens again, we should file [in the forum](https://forum.figma.com/c/plugin-widget-api/plugin-bugs/29), not here.
