### ISSUE TITLE
Please add Token Studio naming convention eg. "Colours.Gray.gray-100" instead of "--Colours-Gray-gray-100"

### ISSUE THREAD

**Issue by mikeysouthwell** [figma/code-snippet-editor-plugin#57]
Hey Jake,

Is it possible to have an option like {{css.background|pascal}} for Token Studio or just generic "dot" notation eg. {{css.background|tokenstudio}} or {{css.background|dots}}

{{css.background|pascal}}
BackgroundColor=Var(ThemeColoursNeutralsNeutral500, #888C84)

{{css.background|tokenstudiol}}
BackgroundColor=Var(Theme.Colours.Neutrals.neutral-500, #888C84)

"css.background": "var(--Theme-Colours-Neutrals-neutral-500, #888C84)",
"variables.fills": "theme-colours-neutrals-neutral-500"

So the last string of text after the dot "." would be unchanged, which in this case is neutral-500.

While the rest would go from "--Theme-Colours-Neutrals-" to "Theme.Colours.Neutrals".

**Comment by jake-figma** [comment]
the best way to handle this is through the [web code syntax](https://help.figma.com/hc/en-us/articles/15145852043927-Create-and-manage-variables#code_syntax) in variables. i dont have control over the output of the CSS, i can only filter it after the fact. you can change what that value is going to be by adding code syntaxes through the variables modal

**Comment by mikeysouthwell** [comment]
Ahh this is exactly what I'm looking for. Thanks Jake! 

I'll use the custom web code syntax for the variables :)

**Comment by mikeysouthwell** [comment]
Hey Jake this only seems to work for colours and not for other elements eg. Radius, sizing etc Is this something you can fix with the plugin or is it a Figma bug?

**Comment by mikeysouthwell** [comment]
Hi Jake, 

I have logged this with Figma Support and I have also emailed you with the details.

This is the ticket number - 1088326.

Can you please follow up with them to confirm if it's an issue with Figma or an issue with your plugin.

**Comment by mikeysouthwell** [comment]
This was my mistake. I was looking at the wrong collection with variables of the same name! 🤦‍♂️ This issue can be closed. The plugin works 🙌
