### ISSUE TITLE
Supporting Code Connect components

### ISSUE THREAD

**Issue by damalekguide** [figma/code-snippet-editor-plugin#59]
Hey,
Are there any plans to implement Code Connect components in this plugin? The outcome would be getting layout code from this plugin and component code from Code Connect ideally in one code snippet.
This could also resolve all issues with components code because we could use Code Connect to map components correctly instead of using snippets to do so knowing that they have limitation unlike Code Connect.

**Comment by jake-figma** [comment]
Great thought! Will pursue this idea once Figma Code Connect is available in the plugin API. That is on the roadmap but there is no exact date for it yet.
