### ISSUE TITLE
Trim whitespace

### ISSUE THREAD

**Issue by gossi** [figma/code-snippet-editor-plugin#7]
I do have this code editor snippet defined:

```hbs
<Button
  {{!property.intent=action}}@intent="{{property.intent}}"
  {{!property.importance=supreme}}@importance="{{property.importance}}"
  {{!property.spacing=0}}@spacing="{{property.spacing}}"
  {{property.state=disabled}}@disabled={{true}}
>
  {{property.text}}
</Button>
```

but if none of the properties are given (ie. the default), then this is the rendered snippet for devs to copy:

```hbs
<Button
>
text
</Button>
```

which sorta looks weird. 

Probably when a couple of lines beginning with qualifiers and they all turn empty, then this is trimmable?

**Comment by jake-figma** [comment]
interesting case here. the quickest fix might be to detect the default state with the new [operators](https://github.com/figma/code-snippet-editor-plugin#operators) i recently added and handle the tag conditionally. it's kinda gross, but logical for the templating language.

```
{{?property.intent=action&property.importance=supreme&property.spacing=0}}{{!property.state=disabled}}<Button>
{{!property.intent=action|property.importance=supreme|property.spacing=0|property.state=disabled}}<Button
...
{{!property.intent=action|property.importance=supreme|property.spacing=0|property.state=disabled}}>
```

the other alternative would be to use [single line syntax](https://github.com/figma/code-snippet-editor-plugin#single-line-syntax) for the whole definition, especially if its rare for all four of your props to render at once.

```
<Button\
{{!property.intent=action}}@intent="{{property.intent}}"\
{{!property.importance=supreme}}@importance="{{property.importance}}"\
{{!property.spacing=0}}@spacing="{{property.spacing}}"\
{{property.state=disabled}}@disabled={{true}}\
\>
  {{property.text}}
</Button>
```

**Comment by jake-figma** [comment]
closing for now, open to other ideas for ways to solve this.
