### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lewishealey** [figma/code-snippet-editor-plugin#8]
Would the plugin support typescript in the future? We have to convert some of these functions into .ts files so it would be amazing to have it all hooked up

**Comment by jake-figma** [comment]
I'm open to this. I am also considering splitting up the files a bit so it's easier to extend. I have been prioritizing no build steps just to make it more approachable for folks as a single file, but we may be hitting our limit there.

To me, the ideal outcome would be supporting ts and multiple files that compile to an easy-to-read static js file tracked in the repo.

**Comment by jake-figma** [comment]
closed by #11 ! looking forward to your feedback on the new structure! tried to keep it simple for everyone to make it as extensible as possible.
