### ISSUE TITLE
Escaping `{{` and`}}`

### ISSUE THREAD

**Issue by gossi** [figma/code-snippet-editor-plugin#9]
I'm using this to generate code for Ember, which uses handlebars as their templating language, so very similar to what this plugin is using. Ember code can look like this:

```hbs
<IconButton @label={{t "some-variable}}" />
```

I want to generate the label part and want to let engineers fill in the string. Here is the code I use for the template of this plugin:

```hbs
<IconButton @label={{t "..."}} />
```

which fails, as I think it can't interpret the `t "..."` part between the curlies.

Is there a way to escape the sequence of `{{`and `}}`?

I'm linking handlebars escaping mechanism for reference: https://handlebarsjs.com/guide/expressions.html#escaping-handlebars-expressions

**Comment by jake-figma** [comment]
I'll add this soon! I think what handlebars proposes is great and would work nicely with the existing language, a single `\` in front of the first curly eg.

```jsx
<IconButton @label=\{{t "..."}} />
```

**Comment by jake-figma** [comment]
There was a bug here, reopening
